all:
	pandoc index.md -c https://hpass.chmd.fr/style.css -o index.html
	pandoc demo1/index.md -o demo1/index.html
	pandoc demo2/index.md -o demo2/index.html
	pandoc demo3/index.md -o demo3/index.html

clean:
	rm -f *.html

